#pragma once

#define W4_RESOURCES_VERSION_MAJOR 0
#define W4_RESOURCES_VERSION_MINOR 3
#define W4_RESOURCES_VERSION_PATCH 0
#define W4_RESOURCES_VERSION 0.3
#define W4_RESOURCES_VERSION_FULL "0.3.0"

#define W4_FRAMEWORK_VERSION_MAJOR 0
#define W4_FRAMEWORK_VERSION_MINOR 1
#define W4_FRAMEWORK_VERSION_PATCH 0
#define W4_FRAMEWORK_VERSION 0.1
#define W4_FRAMEWORK_VERSION_FULL "0.1.0"

#define W4_FRAMEWORK_REVISION "not-included"
